// React项目/box-app/src/components/navbar.jsx
import React, { Component } from 'react';


// const NarBar = (props) => {
//     return (
//        <nav className="navbar navbar-dark bg-dark">
//             <div className="container-fluid">
//                                 <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
//                                     <span className="navbar-toggler-icon"></span>
//                                 </button>
//                                 <span style={{color: "red"}}>Boxes Count: {props.boxesCount}</span>
//                             </div>
//                         </nav>
//         );

// }

class NarBar extends Component {
    state = {  } 

    // constructor () {
    //     super();
    //     console.log("NavBar - Constructor");
    // }

    // componentDidMount() {
    //     console.log("NavBar - Mount");
    // }

    componentDidUpdate () {
        console.log("Navbar - Updated");
    }

    render() { 
        console.log("NavBar - Rendered");
        return (
            <React.Fragment><nav className="navbar navbar-dark bg-dark">
                    <div className="container-fluid">
                        <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span className="navbar-toggler-icon"></span>
                        </button>
                        <span style={{color: "red"}}>Boxes Count: {this.props.boxesCount}</span>
                    </div>
                </nav></React.Fragment>
        );
    }
}
 
export default NarBar;

// vue项目/myserver/src/components/NavBar.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <router-link class="navbar-brand" :to="{name: 'home'}">Myspace</router-link>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <router-link class="nav-link" :to="{name:'home'}">首页</router-link>
                </li>
                <li class="nav-item">
                    <router-link class="nav-link" :to="{name: 'userlist'}">好友列表</router-link>
                </li>
                <li class="nav-item">
                    <router-link class="nav-link" :to="{name: 'userprofile'}">用户动态</router-link>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <router-link class="nav-link" :to="{name: 'login'}">登录</router-link>
                </li>
                <li class="nav-item">
                    <router-link class="nav-link" :to="{name: 'register'}">注册</router-link>
                </li>
            </ul>
            </div>
        </div>
    </nav>
</template>

<script>
export default {
    name: "NavBar"
}
</script>


<style scoped>

</style>
